# Base: Omakase Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Naming/MethodName:
  Enabled: true

Naming/PredicatePrefix:
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/BlockLength:
  Max: 40
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 300

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Lint/UselessAssignment:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true
